### ISSUE TITLE
Uses literal `python` instead of sys.executable

### ISSUE THREAD

**Issue by jayvdb** [NextThought/sphinxcontrib-programoutput#38]
On distros, using `python` will result in Python 2.7 being used, or if being installed into a docker image there will often be no `python` executable unless the python2 packages are installed, and .. 2020 is just around the corner.

Using sys.executable should fix that.

**Comment by jamadden** [comment]
I believe that's only in the tests, which are compatible with both 2 and 3. But if you still see a problem, PRs are welcome!

**Comment by jayvdb** [comment]
Ok, it might just be tests -- that is where I am encountering it, on a build machine without python2 on it.  Not sure if you can see these logs without logging in
https://build.opensuse.org/package/live_build_log/home:jayvdb:py3only/python-sphinxcontrib-programoutput/openSUSE_Tumbleweed/x86_64

**Comment by jamadden** [comment]
Ah, so it appears that machine simply has *no* `python` executable at all on the path.

**Comment by jayvdb** [comment]
Thanks!
