### ISSUE TITLE
Document use with myst

### ISSUE THREAD

**Issue by ssbarnea** [NextThought/sphinxcontrib-programoutput#43]
Some projects started to use markdown instead of RST with Sphinx. It would be really handy to document how to use programoutput with https://myst-parser.readthedocs.io/en/latest/

Updating documentation should not be hard to include a markdown version of it: 

    ```{command-output} python -V
    ```

Still, I need to remark that I observed one case where using shell pipes no longer works: if you command was something like `bash -c "ls | grep foo"`, you may discover that the pipe filtering is lost and you get the full output. Anyway, this is likely a bug in myst argument parsing and not in programoutput extension.

**Comment by jamadden** [comment]
I don't use markdown so I have no idea. Documentation PRs welcome.

**Comment by ssbarnea** [comment]
@jamadden Such a quick reply, deserves a quick PR.
