### ISSUE TITLE
Consider migrating extension under sphinx-contrib

### ISSUE THREAD

**Issue by ssbarnea** [NextThought/sphinxcontrib-programoutput#46]
As we already seen Sphinx extensions getting affected by bitrot, or even dissapearing, it would be a wise move to move this extension under https://github.com/sphinx-contrib

For example I was able to recently resurrect the missing ansi extension that was used in the past by sphinxcontrib-programoutput to render ANSI escapes. The support was removed 4 years ago but we can now put it back as the extension is published on pypi and its code at https://github.com/sphinx-contrib/ansi

**Comment by ssbarnea** [comment]
@jsg2021 @jamadden @cutz @aligon Any reason preventing such a move? I could easily fork it there but I am not sure if this would help making it easier to maintain.

**Comment by jamadden** [comment]
It *used* to live there, but it wasn't getting maintained. It now lives here.

**Comment by ssbarnea** [comment]
LOL. I guess even some organizations would endup unmaintained. I suppose that aspect was sorted in the meanwhile. I already made a fork and made lots of changes.

Once I am done with packaging/testing boring work I plan to combine ansi plugin into programoutput, it makes not much sense to have it standalone and makes any change much harder to implement and having them separated it would mean double the maintenance effort. What do you think?  -- for big pieces of code I would rather have them isolated but that is not the case with programoutput and ansi.

TBW, I sent you an invite.
