### ISSUE TITLE
Add version specific classifiers

### ISSUE THREAD

**Issue by jamadden** [NextThought/sphinxcontrib-programoutput#6]
Docs claim to support py 2.6, do we? What about py3.<reallyold>?

**Comment by elnuno** [comment]
I'll run the tests with tox and report back.

**Comment by elnuno** [comment]
Haha, easier said than done. Most directive, cache and command tests simply error out on Windows. I added some compatibility with https://github.com/elnuno/sphinxcontrib-programoutput/commit/c65743e7018312d8c5208ddd9c9f01d19380b603 , but it's not looking good for test_directive.
